language: node_js
node_js:
    - 13.8
cache:
    directories:
        - "node_modules"
        - "server/node_modules"
        - "client-react/node_modules"
before_install:
    cd server
script: bash run-tests.sh